///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ErrorModalError {
  /*
{
  "status": 401,
  "message": "jwt expired"
} 
*/

  int? status;
  String? message;

  ErrorModalError({this.status, this.message});
  ErrorModalError.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    return data;
  }
}

class ErrorModal {
  /*
{
  "error": {
    "status": 401,
    "message": "jwt expired"
  }
} 
*/

  ErrorModalError? error;

  ErrorModal({this.error});
  ErrorModal.fromJson(Map<String, dynamic> json) {
    error =
        (json['error'] != null)
            ? ErrorModalError.fromJson(json['error'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (error != null) {
      data['error'] = error!.toJson();
    }
    return data;
  }
}
