import 'package:local_app/modal/all_shop_list_items.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class SharedUserListResponse {
  /*
{
  "sharedUserList": [
    {
      "id": 1,
      "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
      "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0",
      "createdAt": "2025-03-25T03:59:48.837Z",
      "updatedAt": "2025-03-25T03:59:48.837Z",
      "user": {
        "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
        "firstName": "Girish",
        "lastName": "Parate",
        "email": "parategirish51@gmail.com",
        "createdAt": "2025-03-22T13:04:05.178Z",
        "updatedAt": "2025-03-22T13:04:05.216Z",
        "deletedAt": "null"
      }
    }
  ]
} 
*/

  List<SharedUserList?>? sharedUserList;

  SharedUserListResponse({this.sharedUserList});
  SharedUserListResponse.fromJson(Map<String, dynamic> json) {
    if (json['sharedUserList'] != null) {
      final v = json['sharedUserList'];
      final arr0 = <SharedUserList>[];
      v.forEach((v) {
        arr0.add(SharedUserList.fromJson(v));
      });
      sharedUserList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (sharedUserList != null) {
      final v = sharedUserList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['sharedUserList'] = arr0;
    }
    return data;
  }
}
