import 'package:local_app/modal/ShopingListModal.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllShopListItemsSharedWithUser {
  /*
{
  "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
  "firstName": "Girish",
  "lastName": "Parate",
  "password": "$2b$08$Iy.wsvkCsVHU4W9xzo767eA9StRYCbquhbDj1scJdJzwp0uhm0zs.",
  "email": "parategirish51@gmail.com",
  "createdAt": "2025-03-22T13:04:05.178Z",
  "updatedAt": "2025-03-22T13:04:05.216Z",
  "deletedAt": "2025-03-22T13:04:05.216Z"
} 
*/

  String? userId;
  String? firstName;
  String? lastName;
  String? password;
  String? email;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  AllShopListItemsSharedWithUser({
    this.userId,
    this.firstName,
    this.lastName,
    this.password,
    this.email,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  AllShopListItemsSharedWithUser.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    firstName = json['firstName']?.toString();
    lastName = json['lastName']?.toString();
    password = json['password']?.toString();
    email = json['email']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    deletedAt = json['deletedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['firstName'] = firstName;
    data['lastName'] = lastName;
    data['password'] = password;
    data['email'] = email;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['deletedAt'] = deletedAt;
    return data;
  }
}

class SharedUserList {
  /*
{
  "id": 1,
  "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
  "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0",
  "createdAt": "2025-03-25T03:59:48.837Z",
  "updatedAt": "2025-03-25T03:59:48.837Z",
  "user": {
    "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
    "firstName": "Girish",
    "lastName": "Parate",
    "password": "$2b$08$Iy.wsvkCsVHU4W9xzo767eA9StRYCbquhbDj1scJdJzwp0uhm0zs.",
    "email": "parategirish51@gmail.com",
    "createdAt": "2025-03-22T13:04:05.178Z",
    "updatedAt": "2025-03-22T13:04:05.216Z",
    "deletedAt": "2025-03-22T13:04:05.216Z"
  }
} 
*/

  int? id;
  String? userId;
  String? shopListId;
  String? createdAt;
  String? updatedAt;
  AllShopListItemsSharedWithUser? user;
  //* New Obj
  MainShopListItem? shopListModal;

  SharedUserList({
    this.id,
    this.userId,
    this.shopListId,
    this.createdAt,
    this.updatedAt,
    this.user,
    this.shopListModal,
  });
  SharedUserList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toString();
    shopListId = json['shopListId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    user =
        (json['user'] != null)
            ? AllShopListItemsSharedWithUser.fromJson(json['user'])
            : null;
    shopListModal =
        (json['shopList'] != null)
            ? MainShopListItem.fromJson(json['shopList'])
            : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['shopListId'] = shopListId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (shopListModal != null) {
      data['shopList'] = shopListModal!.toJson();
    }
    return data;
  }
}

class ShopListItems {
  /*
{
  "shopListItemsId": "6b998e28-8b01-4b2b-8414-97310b834ff3",
  "itemName": "null",
  "description": "null",
  "state": "not-completed",
  "createdAt": "2025-03-26T12:59:46.689Z",
  "updatedAt": "2025-03-26T12:59:46.689Z",
  "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0"
} 
*/

  String? shopListItemsId;
  String? itemName;
  String? description;
  String? state;
  String? createdAt;
  String? updatedAt;
  String? shopListId;
  int? quantity;
  int? price;
  int? id;
  bool? isCompleted;
  bool? isNew;

  ShopListItems({
    this.shopListItemsId,
    this.itemName,
    this.description,
    this.state,
    this.createdAt,
    this.updatedAt,
    this.shopListId,
    this.price,
    this.quantity,
    this.id,
    this.isCompleted,
    this.isNew,
  });
  ShopListItems.fromJson(Map<String, dynamic> json) {
    shopListItemsId = json['shopListItemsId']?.toString();
    itemName = json['itemName']?.toString();
    description = json['description']?.toString();
    state = json['state']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    shopListId = json['shopListId']?.toString();
    quantity = json['quantity']?.toInt();
    price = json['price']?.toInt();
    id = json['id']?.toInt();
    isCompleted = json['isCompleted']?.boolValue;
    isNew = json['isNew']?.boolValue;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['shopListItemsId'] = shopListItemsId;
    data['itemName'] = itemName;
    data['description'] = description;
    data['state'] = state;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['shopListId'] = shopListId;
    data['quantity'] = quantity;
    data['price'] = price;
    data['id'] = id;
    data['isCompleted'] = isCompleted;
    data['isNew'] = isNew;
    return data;
  }

  factory ShopListItems.fromMap(
    Map<String, dynamic> map,
    // bool isCompleted = false,
    // bool isNew,
  ) {
    return ShopListItems(
      id: map['id'] as int?,
      shopListItemsId: map['shopListItemsId'] as String?,
      itemName: map['name'] as String?,
      description: map['description'] as String?,
      state: map['status'] as String?,
      createdAt: map['createdAt'] as String?,
      updatedAt: map['updatedAt'] as String?,
      shopListId: map['shopListId'] as String?,
      price: map['price'] as int?,
      quantity: map['quantity'] as int?,
      // isCompleted: isCompleted,
      // isNew: isNew,
    );
  }
}

class AllShopListItems {
  /*
{
  "shopList": {
    "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0",
    "shopListName": "Dmart List UPDATE",
    "description": "Dmart List",
    "state": "not-completed",
    "createdAt": "2025-03-22T01:02:00.244Z",
    "updatedAt": "2025-03-22T01:02:00.244Z",
    "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1"
  },
  "shopListItem": [
    {
      "shopListItemsId": "6b998e28-8b01-4b2b-8414-97310b834ff3",
      "itemName": "null",
      "description": "null",
      "state": "not-completed",
      "createdAt": "2025-03-26T12:59:46.689Z",
      "updatedAt": "2025-03-26T12:59:46.689Z",
      "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0"
    }
  ],
  "sharedWith": [
    {
      "id": 1,
      "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
      "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0",
      "createdAt": "2025-03-25T03:59:48.837Z",
      "updatedAt": "2025-03-25T03:59:48.837Z",
      "user": {
        "userId": "bb8a98bf-5249-4989-aa05-0834bf7f8fb2",
        "firstName": "Girish",
        "lastName": "Parate",
        "password": "$2b$08$Iy.wsvkCsVHU4W9xzo767eA9StRYCbquhbDj1scJdJzwp0uhm0zs.",
        "email": "parategirish51@gmail.com",
        "createdAt": "2025-03-22T13:04:05.178Z",
        "updatedAt": "2025-03-22T13:04:05.216Z",
        "deletedAt": "2025-03-22T13:04:05.216Z"
      }
    }
  ]
} 
*/

  MainShopListItem? shopList;
  List<ShopListItems?>? shopListItem;
  List<SharedUserList?>? sharedWith;
  bool? isOwner;

  AllShopListItems({
    this.shopList,
    this.shopListItem,
    this.sharedWith,
    this.isOwner,
  });
  AllShopListItems.fromJson(Map<String, dynamic> json) {
    shopList =
        (json['shopList'] != null)
            ? MainShopListItem.fromJson(json['shopList'])
            : null;
    if (json['shopListItem'] != null) {
      final v = json['shopListItem'];
      final arr0 = <ShopListItems>[];
      v.forEach((v) {
        arr0.add(ShopListItems.fromJson(v));
      });
      shopListItem = arr0;
    }
    if (json['sharedWith'] != null) {
      final v = json['sharedWith'];
      final arr0 = <SharedUserList>[];
      v.forEach((v) {
        arr0.add(SharedUserList.fromJson(v));
      });
      sharedWith = arr0;
    }
    isOwner = json['isOwner'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (shopList != null) {
      data['shopList'] = shopList!.toJson();
    }
    if (shopListItem != null) {
      final v = shopListItem;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['shopListItem'] = arr0;
    }
    if (sharedWith != null) {
      final v = sharedWith;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['sharedWith'] = arr0;
    }
    data['isOwner'] = isOwner;
    return data;
  }
}
