///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommonItemsItems {
  /*
{
  "commonItemsId": "2608b9fc-b5fa-4f0d-b2ab-3df8a787877c",
  "itemName": "Passta update",
  "description": "A passta",
  "quantity": 1,
  "price": 0,
  "createdAt": "2025-03-30T01:52:23.798Z",
  "updatedAt": "2025-03-30T04:23:12.238Z",
  "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1"
} 
*/

  String? commonItemsId;
  String? itemName;
  String? description;
  int? quantity;
  int? price;
  String? createdAt;
  String? updatedAt;
  String? userId;

  CommonItemsItems({
    this.commonItemsId,
    this.itemName,
    this.description,
    this.quantity,
    this.price,
    this.createdAt,
    this.updatedAt,
    this.userId,
  });
  CommonItemsItems.fromJson(Map<String, dynamic> json) {
    commonItemsId = json['commonItemsId']?.toString();
    itemName = json['itemName']?.toString();
    description = json['description']?.toString();
    quantity = json['quantity']?.toInt();
    price = json['price']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    userId = json['userId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['commonItemsId'] = commonItemsId;
    data['itemName'] = itemName;
    data['description'] = description;
    data['quantity'] = quantity;
    data['price'] = price;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['userId'] = userId;
    return data;
  }
}

class CommonItems {
  /*
{
  "items": [
    {
      "commonItemsId": "2608b9fc-b5fa-4f0d-b2ab-3df8a787877c",
      "itemName": "Passta update",
      "description": "A passta",
      "quantity": 1,
      "price": 0,
      "createdAt": "2025-03-30T01:52:23.798Z",
      "updatedAt": "2025-03-30T04:23:12.238Z",
      "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1"
    }
  ]
} 
*/

  List<CommonItemsItems?>? items;

  CommonItems({this.items});
  CommonItems.fromJson(Map<String, dynamic> json) {
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <CommonItemsItems>[];
      v.forEach((v) {
        arr0.add(CommonItemsItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}
