///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OperationResponse {
  /*
{
  "success": true
} 
*/

  bool? success;

  OperationResponse({this.success});
  OperationResponse.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}
