import 'package:local_app/Networking/modal/main_shop_list.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ShopListItemResponse {
  /*
{
  "allShopListItem": [
    {
      "shopListItemsId": "69eb27cf-4f08-4c84-91ac-0175558b0fd7",
      "name": "Dmart List Update me",
      "itemInfo": "Dmart Listoo",
      "state": "completed",
      "createdAt": "2025-03-16T14:10:23.089Z",
      "updatedAt": "2025-03-19T02:13:40.198Z",
      "shopListId": "36516533-c7d0-45b4-9f80-6a3b687691a5"
    }
  ]
} 
*/

  List<AllShopListMainAllShopListsShopListItems?>? allShopListItem;

  ShopListItemResponse({this.allShopListItem});
  ShopListItemResponse.fromJson(Map<String, dynamic> json) {
    if (json['allShopListItem'] != null) {
      final v = json['allShopListItem'];
      final arr0 = <AllShopListMainAllShopListsShopListItems>[];
      v.forEach((v) {
        arr0.add(AllShopListMainAllShopListsShopListItems.fromJson(v));
      });
      allShopListItem = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (allShopListItem != null) {
      final v = allShopListItem;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['allShopListItem'] = arr0;
    }
    return data;
  }
}
