import 'dart:ffi';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MainShopListItem {
  /*
{
  "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0",
  "shopListName": "Dmart List UPDATE",
  "description": "Dmart List",
  "state": "not-completed",
  "createdAt": "2025-03-22T01:02:00.244Z",
  "updatedAt": "2025-03-22T01:02:00.244Z",
  "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1"
} 
*/

  String? shopListId;
  String? shopListName;
  String? description;
  String? state;
  String? createdAt;
  String? updatedAt;
  String? userId;
  String? user_id;
  String? superBaseId;
  int? id;
  bool? isCompleted;
  bool? isNew;

  MainShopListItem({
    this.shopListId,
    this.shopListName,
    this.description,
    this.state,
    this.createdAt,
    this.updatedAt,
    this.userId,
    this.user_id,
    this.id,
    this.superBaseId,
    this.isCompleted,
    this.isNew,
  });
  MainShopListItem.fromJson(Map<String, dynamic> json) {
    if (json['id'] != null) {
      if (json['id'] is String) {
        superBaseId = json['id'];
      } else {
        id = json['id'] as int?;
      }
    }
    shopListId = json['shopListId']?.toString();
    shopListName = json['shopListName']?.toString();
    description = json['description']?.toString();
    state = json['state']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    userId = json['userId']?.toString();
    isCompleted = json['isCompleted'] as bool?;
    isNew = json['isNew'] as bool?;
    user_id = json['user_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (shopListId != null) {
      data['shopListId'] = shopListId;
    }
    if (shopListName != null) {
      data['shopListName'] = shopListName;
    }
    if (description != null) {
      data['description'] = description;
    }
    if (state != null) {
      data['state'] = state;
    }
    if (createdAt != null) {
      data['createdAt'] = createdAt;
    }
    if (updatedAt != null) {
      data['updatedAt'] = updatedAt;
    }
    if (userId != null) {
      data['userId'] = userId;
    }
    if (id != null) {
      data['id'] = id;
    }
    if (superBaseId != null) {
      data['id'] = superBaseId;
    }
    if (isCompleted != null) {
      data['isCompleted'] = isCompleted;
    }
    if (isNew != null) {
      data['isNew'] = isNew;
    }
    if (user_id != null) {
      data['user_id'] = user_id;
    }
    return data;
  }

  factory MainShopListItem.fromMap(
    Map<String, dynamic> map,
    bool isCompleted,
    bool isNew,
  ) {
    return MainShopListItem(
      id: map['id'] as int?,
      // superBaseId: superBaseId,
      shopListId: map['shopListId']?.toString(),
      shopListName: map['title']?.toString(),
      description: map['description']?.toString(),
      state: map['state']?.toString(),
      createdAt: map['createdAt']?.toString(),
      updatedAt: map['updatedAt']?.toString(),
      userId: map['userId']?.toString(),
      isCompleted: isCompleted,
      isNew: isNew,
    );
  }
}

class ShopListModal {
  /*
{
  "shopList": [
    {
      "shopListId": "a1891f5c-d57b-46a4-81fe-4f8014805db0",
      "shopListName": "Dmart List UPDATE",
      "description": "Dmart List",
      "state": "not-completed",
      "createdAt": "2025-03-22T01:02:00.244Z",
      "updatedAt": "2025-03-22T01:02:00.244Z",
      "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1"
    }
  ]
} 
*/

  List<MainShopListItem?>? shopList;

  ShopListModal({this.shopList});
  ShopListModal.fromJson(Map<String, dynamic> json) {
    if (json['shopList'] != null) {
      final v = json['shopList'];
      final arr0 = <MainShopListItem>[];
      v.forEach((v) {
        arr0.add(MainShopListItem.fromJson(v));
      });
      shopList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (shopList != null) {
      final v = shopList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['shopList'] = arr0;
    }
    return data;
  }
}
