///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserEmailListResponseUsers {
  /*
{
  "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1",
  "email": "parategirish50@gmail.com"
} 
*/

  String? userId;
  String? email;

  UserEmailListResponseUsers({this.userId, this.email});
  UserEmailListResponseUsers.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    email = json['email']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['email'] = email;
    return data;
  }
}

class UserEmailListResponse {
  /*
{
  "users": [
    {
      "userId": "41610f45-bb19-4192-b8b8-05ed1edb61a1",
      "email": "parategirish50@gmail.com"
    }
  ]
} 
*/

  List<UserEmailListResponseUsers?>? users;

  UserEmailListResponse({this.users});
  UserEmailListResponse.fromJson(Map<String, dynamic> json) {
    if (json['users'] != null) {
      final v = json['users'];
      final arr0 = <UserEmailListResponseUsers>[];
      v.forEach((v) {
        arr0.add(UserEmailListResponseUsers.fromJson(v));
      });
      users = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (users != null) {
      final v = users;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['users'] = arr0;
    }
    return data;
  }
}
